#! /usr/bin/env bash
# A crontab that downloads the list of expired and
# soon-to-be expired domains from domainname.shop
# once a dag (22:00)
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SOURCE_DIR"
source config.sh

TIMESTAMP="$(date +%F%T | tr ':' '-')"

if [ -d "$PWD/$STORAGE" ];  then
  find "$PWD/$STORAGE" -type f -name '*.html' -exec cat {} \; | \
  cat - "${DOMAINS}" 2>/dev/null | \
  "${MCN_TOOLS}/default_extract" > ./tmp.list
  cat ./*"$DOMAINS" ./tmp.list | sort | uniq > "$TIMESTAMP-$DOMAINS"
  rm -f ./tmp.list
fi
