#! /usr/bin/env bash
# Info: 
# Download: 
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SOURCE_DIR}"
source config.sh

ENWIKI="https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-externallinks.sql.gz"
NOWIKI="https://dumps.wikimedia.org/nowiki/latest/nowiki-latest-externallinks.sql.gz"
NNWIKI="https://dumps.wikimedia.org/nnwiki/latest/nnwiki-latest-externallinks.sql.gz"

function dw {
    BN="$(basename "$1")"
    if [ ! -e "$BN" ]; then
        echo "Fail to find ${BN}, downloading" 1>&2;
        wget --timestamping "${1}";
    else
        echo "Found ${BN}" 1>&2;
    fi
}

dw "${ENWIKI}"
dw "${NOWIKI}"
dw "${NNWIKI}"

#if [ ! -e "$OUT" ] || [ "x$1" = "x--update-list" ]; then
#  echo "Extracting and grepping $IN into ${OUT}.tmp" 1>&2;
  #gzip --stdout -d "$IN" | sed -e 's/),(/\n/g' | grep -a -F '.no' | $BASE/scraper/urldecode
